### ISSUE TITLE
Releasing a New ObsPy Version

### ISSUE THREAD

**Issue by krischer** [obspy/obspy#1243]
Hi all,

it has already been way too long since the last ObsPy release and thus we should release as soon as possible. The major hurdle was #1039 but that is basically done now.

### Version Number

Which number should it be? Candidates are `0.11` and `1.0`. `0.11` is the natural progression but I think we are stable enough to call it `1.0`. Another reason for calling it `1.0` is that we did some fairly significant internal restructuring of ObsPy and that (while we try to limit it as much as possible) might affect users. Calling it `1.0` states it fairly clearly that something is new. Other opinions?

### Schedule

After the relevant todos below are done (hopefully this week): Tag a release candidate version and write to the mailing list for people to test it with their codes. We made significant changes in this version and want to ensure it can still run existing codes of other people. A week later we will release the new version.

### ToDo

- [x] #1039 - Deprecation Reroutes (@krischer)
- [x] #1239 - Baseline images for matplotlib 1.5 (whoever feels like it - otherwise @megies ;-) )
- [x] Review all milestones and either fix or bump to the next release. Why do we have a milestone for `0.11.x`? [0.11.x](https://github.com/obspy/obspy/milestones/0.11.x), [0.11.0](https://github.com/obspy/obspy/milestones/0.11.0), [0.10.x](https://github.com/obspy/obspy/milestones/0.10.x) (all)
- [x] Draft a detailed `What's New` wiki page in the vein of [this](https://github.com/obspy/obspy/wiki/What's-New-in-ObsPy-0.10.1) - I already created the page here: https://github.com/obspy/obspy/wiki/What's-New-in-ObsPy-1.0  (please all add to this - @jkmacc-LANL can you add a section about how to use the new `SACTrace` object as I think quite a number of people used the old SacIO classes directly)
- [x] Check all links in the documentation.
- [x] Update docker tests to latest distros (@krischer).
- [x] conda packages for..
    - [x] Linux
    - [x] OSX
    - [x] windows
- [x] Windows pypi packages (@barsch)
- [x] debian packages (@megies, see https://www.geophysik.uni-muenchen.de/~megies/obspy-1.0.0rc1.debs/, note: fix static version number)
- [x] redhat/centos packages (@qulogic)
- [x] macports packages (@petrrr)
- [x] Get a new DOI on zenodo
    - 0.10.3: 10.5281/zenodo.46150
    - 1.0.0: 10.5281/zenodo.46151
- [x] merge #1234
- [x] fix #1247 
- [x] merge #1240 
- [x] last touches in #1192
- [x] check if any bug fixes need to be cherry-picked from `releases`
- [x] update branching model
- [x] check CHANGELOG version numbers
- [x] #1258 

Feel free to edit this post to add things I forgot.

**Comment by megies** [comment]
:+1: for 1.0

**Comment by barsch** [comment]
1.0.0 sounds fair ..

**Comment by ThomasLecocq** [comment]
"version 1"
:)

**Comment by jkmacc-LANL** [comment]
1.0 sounds great!  I'll certainly add some `SACTrace` instruction, and fix those warnings this week.

**Comment by claudiodsf** [comment]
:+1: for 1.0

**Comment by jkmacc-LANL** [comment]
The `SACTrace` section got a bit long; feel free to trim.

**Comment by trichter** [comment]
A new release would be great!

**Comment by claudiodsf** [comment]
Concerning the `SACTrace` section in the wiki, does this imply that `SACTrace` is now the recommended way of dealing with sac traces, as opposite to use `obspy.read()` and `obspy.write()` and `Trace` objects?
I think that the wiki page should be clear on that.

Also, we should maybe indicate some change in the way `Trace.stats.sac` behaves which might potentially break some application (at least mine ;): so far, if an header field was not defined, it was still available in `Trace.stats.sac` with its undefined value (`-12345`). With the new implementation, requesting a header field which is not defined raises an `AttributeError`.

**Comment by jkmacc-LANL** [comment]
@claudiodsf I've added language to make it clear that `SACTrace` isn't the preferred way to work with SAC files.  Also, I've specified the minor changes in `obspy.read`, and how to get all those undefined values if you wanted them.  Thanks!

**Comment by claudiodsf** [comment]
@jkmacc-LANL Great, thanks!

**Comment by megies** [comment]
@obspy/packagers 1.0.0rc1 source dist zipball is up for testing:
https://www.geophysik.uni-muenchen.de/~megies/obspy-1.0.0rc1.zip

**Comment by QuLogic** [comment]
`obspy.signal.spectral_estimation.PPSD.plot(..., cumulative=True)` generates a warning by default if you do not also specify `max_percentage=None` because `max_percentage=30` by default. Maybe `max_percentage` should be set to `None` by default and then assigned `30` if `cumulative=False`?

**Comment by megies** [comment]
> obspy.signal.spectral_estimation.PPSD.plot(..., cumulative=True) generates a warning by default if you do not also specify max_percentage=None because max_percentage=30 by default. Maybe max_percentage should be set to None by default and then assigned 30 if cumulative=False?

Oh, yeah, right. I saw it a couple of times before but never got round to fix it.. :+1: for the proposed fix.

**Comment by QuLogic** [comment]
`travelTimePlot` is also causing warnings in docs, and could have been removed in this release, but we don't really have a one-to-one replacement method in `TauPyModel`. This one can wait for a later release, I'd say.

**Comment by megies** [comment]
Debian/Ubuntu packages of `1.0.0rc1` are up for testing: https://www.geophysik.uni-muenchen.de/~megies/obspy-1.0.0rc1.debs/

**Comment by QuLogic** [comment]
Currently, `get_untracked_files_from_git` [raises a `ValueError`](https://github.com/obspy/obspy/blob/master/obspy/core/util/misc.py#L252) if the git root directory is unexpected. My rpm specs are in git, so it gets confused since the build directory is also in a git-controlled working tree (just not obspy's); is it really necessary to raise an error there and not just return an empty list?

It's not a big deal since it only means I can't run pep8/flake8 in the docs/tests.

**Comment by krischer** [comment]
Lets remove all the deprecated things next week after releasing 1.0.0. I think it should get rid of a large number of documentation warnings.

**Comment by ThomasLecocq** [comment]
one failure on my win64 box:
```
Traceback (most recent call last):
File "C:\Anaconda\lib\site-packages\obspy-1.0.0rc1-py2.7-win-amd64.egg\obspy\signal\tests\test_invsim.py", line 424, in test_evalresp_seed_identifiers_work
self.assertIn(b"no response found for", out.stderr.lower())
AssertionError: 'no response found for' not found in ''
```

**Comment by petrrr** [comment]
I get a ugly `TopologyException` in test `test_catalog_plot_global`

```
test_catalog_plot_global (obspy.core.tests.test_event.CatalogCartopyTestCase) ... TopologyException: side location conflict at -1.0605929297246731e-09 -9020047.8480736464
ok

```

**Comment by krischer** [comment]
@petrrr Are you using the latest cartopy? I don't think that's an issue we can fix on our side.

**Comment by petrrr** [comment]
Yes, I am on cartopy 0.13.1 here.

**Comment by petrrr** [comment]
I get some Deprecation warnings from tests. Is this something you would like to fix?

**Comment by krischer** [comment]
Yes definitely! Though some might already be fixed in #1256.

**Comment by petrrr** [comment]
Is `nose` not a dependency? Not anymore ???

**Comment by krischer** [comment]
Not directly but matplotlib needs it - numpy also. I think `np.testing` which we use a lot also requires it for some things.

**Comment by megies** [comment]
New source dist zipball, RC2: https://www.geophysik.uni-muenchen.de/~megies/obspy-1.0.0rc2.zip

**Comment by krischer** [comment]
> one failure on my win64 box:
> 
> Traceback (most recent call last):
> File "C:\Anaconda\lib\site-packages\obspy-1.0.0rc1-py2.7-win-amd64.egg\obspy\signal\tests\test_invsim.py", line 424, in test_evalresp_seed_identifiers_work
> self.assertIn(b"no response found for", out.stderr.lower())
> AssertionError: 'no response found for' not found in ''

@ThomasLecocq Does it print `no response found for` in the terminal?  In that case the `CatchOutput` context manager would just not catch the line. Otherwise it would not be generated which should not be.

**Comment by petrrr** [comment]
I still get some warnings which result in ERRORs, but not sure we can do much about this:
```
matplotlib.cbook.MatplotlibDeprecationWarning: This has been deprecated in mpl 1.5, please use the
axes property.  A removal date has not been set.
```
Probably we cannot do much about this as long as you want to support older mpl.

Then some `User warnings`, do they occur intentionally in the tests?

**Comment by QuLogic** [comment]
I think that matplotlib one is from Cartopy and will be fixed in 0.14.

**Comment by petrrr** [comment]
I just committed an update to Macports `py-obspy-devel` port, which now installs the release candidate (1.0.0rc2) and should build the binaries in a while. Should be mostly fine as I already tests quite a bit locally. The port now also installs man pages and uses the port select mechanism.

**Comment by petrrr** [comment]
Have I hit a wrong check box? 
I intended to check the macports box but when getting back to it I was unchecked. 
So you might wanna check if I have not done any damage ...

**Comment by krischer** [comment]
Looks good to me.

**Comment by megies** [comment]
From feedback we got, this should probably be the last RC we need and I think we can release tomorrow..
https://www.geophysik.uni-muenchen.de/~megies/obspy-1.0.0rc3.zip

**Comment by megies** [comment]
https://www.geophysik.uni-muenchen.de/~megies/obspy-1.0.0rc4.zip

**Comment by ThomasLecocq** [comment]
I think we should call it 0.11 :-)

*trolling mode on* :)

**Comment by mbyt** [comment]
And I really like 1.0 :-). Good job guys, the release notes are great by the way!

**Comment by megies** [comment]
Hopefully last RC: https://www.geophysik.uni-muenchen.de/~megies/obspy-1.0.0rc5.zip

**Comment by krischer** [comment]
I'm done with the whats new page from my point of view. Please add/edit whatever I missed/did wrong: https://github.com/obspy/obspy/wiki/What's-New-in-ObsPy-1.0

**Comment by megies** [comment]
https://www.geophysik.uni-muenchen.de/~megies/obspy-1.0.0rc7.zip

**Comment by megies** [comment]
https://www.geophysik.uni-muenchen.de/~megies/obspy-1.0.0rc8.zip

**Comment by megies** [comment]
:tada:

**Comment by QuLogic** [comment]
Everything is checked here; I guess we can close this one.
